### ISSUE TITLE
Help required with permission system on the tenant side

### ISSUE THREAD

**Issue by speightashley** [Corvia/django-tenant-users#463]
I have a public tenant set up where I can log in as a user, create a tenant and manage those tenants on the public side (when authenticated of course).

The tenants that I create, I want to be able to click the tenant link on the public side and go to the tenant that I have just created.

I can do this but it's publicly available when I type the URL in the browser. E.g. mytenant.localhost:8000

I want this to be a logged in only activity.

When I introduce a loginrequired decorator or loginrequiredmixin, it fails to recognise that I am logged in already on the pubic side.

Instead, I'm pushed towards http://tenant2.localhost:8000/accounts/login/?next=/

I'm probably missing something really stupid here but any help is appreciated.

My understanding is that tenant_users allows for being logged in on the public side and thus not needed to log in on the tenant side.

**Comment by Dresdn** [comment]
The authentication and session management is handled via core Django. What you're looking for is to use cross-domain cookies (an authentication session at foo.domain.com will be valid for bar.domain.com)

Take a look here: https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-SESSION_COOKIE_DOMAIN

Also, a good tip would be to work and validate settings with https (since that's probably what will be in production), so I typically front my local instance with Caddy (via Docker) using:

Caddyfile:
`
local.test {
  tls internal
  reverse_proxy host.docker.internal:7000
}

*.local.test {
  tls internal
  reverse_proxy host.docker.internal:7000
}
`

Then you can test that a login at https://local.test will indeed authenticate you to https://tenant2.local.test using the same cookie.

**Comment by speightashley** [comment]
@Dresdn Can you do me a favor and show me your Dockerfile and docker-compose.yml? I've never used Caddy before and I'm trying to set it up as you say but having difficulty. Any help would be appreciated.

**Comment by Dresdn** [comment]
Sure - here's the service from the `docker-compose.yml` I use:

```
  caddy:
    image: "caddy/caddy"
    container_name: "caddy"
    hostname: "caddy"
    restart: unless-stopped
    network_mode: "bridge"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```

`caddy/Caddyfile`:

```
{
  admin off
}

local.test {
  tls internal
  reverse_proxy host.docker.internal:7000
}

*.local.test {
  tls internal
  reverse_proxy host.docker.internal:7000
}
```

Just lookup setting up a local resolver for the `.test` TLD or whatever domain you want to use, so it automatically resolves to your local machine.
